Anykernel2: update to latest template

diff --git a/Anykernel2/META-INF/com/google/android/update-binary b/Anykernel2/META-INF/com/google/android/update-binary
--- a/Anykernel2/META-INF/com/google/android/update-binary
+++ b/Anykernel2/META-INF/com/google/android/update-binary
@@ -14,7 +14,7 @@ ui_print() {
 }
 show_progress() { echo "progress $1 $2" > $OUTFD; }
 set_perm_recursive() {
-  dirs=$(echo $* | awk '{ print substr($0, index($0,$5)) }');
+  dirs=$(echo $* | $bb awk '{ print substr($0, index($0,$5)) }');
   for i in $dirs; do
     chown -R $1.$2 $i; chown -R $1:$2 $i;
     find "$i" -type d -exec chmod $3 {} +;
@@ -23,32 +23,38 @@ set_perm_recursive() {
 }
 file_getprop() { grep "^$2" "$1" | cut -d= -f2; }
 getprop() { test -e /sbin/getprop && /sbin/getprop $1 || file_getprop /default.prop $1; }
-abort() { ui_print "$*"; exit 1; }
+abort() { ui_print "$*"; umount /system; umount /data; exit 1; }
 
 show_progress 1.34 4;
 ui_print " ";
-mkdir -p /tmp/anykernel;
+mkdir -p /tmp/anykernel/bin;
 cd /tmp/anykernel;
 unzip -o "$ZIP";
+if [ $? != 0 -o -z "$(ls /tmp/anykernel/tools)" ]; then
+  abort "Unzip failed. Aborting...";
+fi;
+chmod -R 755 /tmp/anykernel/tools /tmp/anykernel/bin;
+bb=/tmp/anykernel/tools/busybox;
 
 ui_print "$(file_getprop /tmp/anykernel/anykernel.sh kernel.string)";
 ui_print "**********************************";
 ui_print "Optimus Kernel by Flashhhh";
 ui_print "Optimizing.... ";
 ui_print "**********************************";
-/sbin/busybox mount /system;
+mount -o ro -t auto /system;
+mount /data;
 
 if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.devicecheck)" == 1 ]; then
   ui_print "Checking device...";
-  ui_print " ";
   for i in 1 2 3 4 5; do
     testname="$(file_getprop /tmp/anykernel/anykernel.sh device.name$i)";
     if [ "$(getprop ro.product.device)" == "$testname" -o "$(getprop ro.build.product)" == "$testname" ]; then
+      ui_print "$testname";
       match=1;
     fi;
   done;
+  ui_print " ";
   if [ "$match" != 1 ]; then
-    umount /system;
     abort "Unsupported device. Aborting...";
   fi;
 fi;
@@ -56,22 +62,31 @@ fi;
 if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.initd)" == 1 ]; then
   ui_print "Creating init.d...";
   ui_print " ";
+  mount -o remount,rw -t auto /system;
   mkdir /system/etc/init.d;
   set_perm_recursive 0 0 0755 0755 /system/etc/init.d;
+  mount -o remount,ro -t auto /system;
 fi;
 
 ui_print "Installing kernel...";
-/sbin/sh /tmp/anykernel/anykernel.sh $2;
+for i in $($bb --list); do
+  $bb ln -s $bb /tmp/anykernel/bin/$i;
+done;
+if [ $? != 0 -o -z "$(ls /tmp/anykernel/bin)" ]; then
+  abort "Recovery busybox setup failed. Aborting...";
+fi;
+PATH="/tmp/anykernel/bin:$PATH" $bb ash /tmp/anykernel/anykernel.sh $2;
 if [ $? != "0" ]; then
-  umount /system;
   abort;
 fi;
 
 if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.modules)" == 1 ]; then
-  ui_print "Pushing modules...";
   ui_print " ";
-  cp -f /tmp/anykernel/modules/* /system/lib/modules/;
+  ui_print "Pushing modules...";
+  mount -o remount,rw -t auto /system;
+  cp -rf /tmp/anykernel/modules/* /system/lib/modules/;
   set_perm_recursive 0 0 0755 0644 /system/lib/modules;
+  mount -o remount,ro -t auto /system;
 fi;
 
 if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.cleanup)" == 1 ]; then
@@ -79,6 +94,7 @@ if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.cleanup)" == 1 ]; then
 fi;
 
 umount /system;
+umount /data;
 ui_print " ";
 ui_print "Done!";
 
